### ISSUE TITLE
First Checklist

### ISSUE THREAD

**Issue by redSW20** [rls5113/team6#7]
## User Stories

As a user I would like to be able to compare rental rates on cars, availability(model, date), closest to my location, and availability of provided insurance.

## What We Need Done!

- [ ] index.html--- Format HTML(set divs, User input form, )
- [ ] index.html--- Link in libraries needed(boootstrap, jquery, etc.)
- [ ] style.css--- add in some basic styling to help with creation and formatting
- [ ] main.js--- Start pseudocoding everything we need and where we need it
